from enum import Enum


class FinancialTransactionSourceType(str, Enum):
    OPENING_BALANCE = "OPENING_BALANCE"
    PAYMENT = "PAYMENT"
    EXPENSE = "EXPENSE"
    UTILITY_BILL = "UTILITY_BILL"
    TAX_RECORD = "TAX_RECORD"
    PERSONAL_DEPOSIT = "PERSONAL_DEPOSIT"
    PERSONAL_WITHDRAWAL = "PERSONAL_WITHDRAWAL"
    TRANSFER = "TRANSFER"
    OTHER = "OTHER"