from enum import Enum


class SystemSettingKey(str, Enum):
    EMAIL = "EMAIL"
    STORAGE = "STORAGE"


class SystemSettingConfigKey(str, Enum):
    SMTP_HOST = "SMTP_HOST"
    SMTP_PORT = "SMTP_PORT"
    SMTP_USE_TLS = "SMTP_USE_TLS"
    NOREPLY_USER_NAME = "NOREPLY_USER_NAME"
    NOREPLY_FROM_ADDRESS = "NOREPLY_FROM_ADDRESS"
    NOREPLY_VERIFIED_AT = "NOREPLY_VERIFIED_AT"
    NOREPLY_VERIFICATION_TOKEN = "NOREPLY_VERIFICATION_TOKEN"
    NOREPLY_VERIFICATION_SENT_AT = "NOREPLY_VERIFICATION_SENT_AT"
    NOREPLY_VERIFICATION_EXPIRES_AT = "NOREPLY_VERIFICATION_EXPIRES_AT"
    SYSTEM_USER_NAME = "SYSTEM_USER_NAME"
    SYSTEM_FROM_ADDRESS = "SYSTEM_FROM_ADDRESS"
    SYSTEM_VERIFIED_AT = "SYSTEM_VERIFIED_AT"
    SYSTEM_VERIFICATION_TOKEN = "SYSTEM_VERIFICATION_TOKEN"
    SYSTEM_VERIFICATION_SENT_AT = "SYSTEM_VERIFICATION_SENT_AT"
    SYSTEM_VERIFICATION_EXPIRES_AT = "SYSTEM_VERIFICATION_EXPIRES_AT"
    STORAGE_PROVIDER = "STORAGE_PROVIDER"
    STORAGE_LOCAL_FOLDER = "STORAGE_LOCAL_FOLDER"
    STORAGE_S3_BUCKET = "STORAGE_S3_BUCKET"
    STORAGE_S3_REGION = "STORAGE_S3_REGION"
    STORAGE_S3_ENDPOINT_URL = "STORAGE_S3_ENDPOINT_URL"
    STORAGE_S3_BASE_PREFIX = "STORAGE_S3_BASE_PREFIX"
    STORAGE_S3_USE_PATH_STYLE = "STORAGE_S3_USE_PATH_STYLE"
    STORAGE_S3_ACCESS_KEY_ID = "STORAGE_S3_ACCESS_KEY_ID"


class SystemSettingSecretKey(str, Enum):
    NOREPLY_PASSWORD = "NOREPLY_PASSWORD"
    SYSTEM_PASSWORD = "SYSTEM_PASSWORD"
    STORAGE_S3_SECRET_ACCESS_KEY = "STORAGE_S3_SECRET_ACCESS_KEY"
